language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - stable
install:
  - yarn
script:
  - yarn lint
  - yarn test
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
